services:    
  ollama:
    container_name: ollama

    #runtime: amd
    build:
      context: .
      dockerfile: dockerfile.vulkan

    environment:
     # - AMD_VISIBLE_DEVICES=all
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_VULKAN=1

    devices:
      - /dev/dri:/dev/dri
    shm_size: 16g
    volumes:
      - /data/volumes-data/models/ollama:/root/.ollama/models

    tty: true
    restart: unless-stopped

    # network_mode: "host"
    networks:
      - share-net
    dns:
      - 1.1.1.1
      - 8.8.8.8

volumes:
  ollama:

networks:
  share-net:
    name: share-net
    external: true

