# Stage 1: import amd-gpu dev env
FROM ubuntu:25.10 AS ollama-builder

RUN mv /etc/apt/sources.list.d /etc/apt/sources.list.d.bak
RUN mkdir -p /etc/apt/sources.list.d
RUN cp /etc/apt/sources.list.d.bak/ubuntu.sources /etc/apt/sources.list.d/

RUN apt-get update

RUN apt-get install zstd curl pciutils -y

RUN curl -fsSL https://ollama.com/install.sh | sh

ENV OLLAMA_VULKAN=1
CMD ["/usr/local/bin/ollama", "serve"]
