include:
  - ../../compose-include.yaml

services:    
  ollama:
    container_name: ${OLLAMA_NAME?ollama name not set! }

    #runtime: amd
    build:
      context: .
      dockerfile: dockerfile.vulkan

    environment:
     # - AMD_VISIBLE_DEVICES=all
      - OLLAMA_HOST=0.0.0.0:${OLLAMA_PORT:-11434}
      - OLLAMA_VULKAN=1

    devices:
      - /dev/dri:/dev/dri
    shm_size: 16g
    volumes:
      - ${ROOT_DATA}/models/ollama:/root/.ollama/models

    tty: true
    restart: unless-stopped

    # network_mode: "host"
    networks:
      - ${SHARED_NETWORK?net issue.}
    dns:
      - 1.1.1.1
      - 8.8.8.8

volumes:
  ollama:
